name: Scheduled Script

on:
  schedule:
    - cron: '0 8-17 * * *'  # Schedules to run every day at 6 AM UTC

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          # Install your required Python packages here
          pip install pandas openpyxl gspread PyDrive
  
      - name: Run script
        run: |
          python your_script.py # Replace with actual script name
